global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 添加您本地应用的监控配置
  # 例如，如果您的应用暴露了 metrics 端点：
  # - job_name: 'your-app'
  #   static_configs:
  #     - targets: ['your-app-host:your-app-port']
  #   metrics_path: '/custom-metrics'
